/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
//const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
//  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
//};

//export default sidebars;
module.exports = {
  tutorialSidebar:[
    {
      type: 'category',
      label: 'NCM Self Service 101',
      items: ['what_is_calm/what_is_calm',
              'calm_project/calm_project',
              'calm_project/calm_environment',
              'what_is_calm/blueprint',
              'what_is_calm/application',
              'what_is_calm/runbook',
              'ncm_marketplace2/ncm_marketplace2',
              'ncm_windows_ad3/ncm_windows_ad3',
              'ncm_windows_ad3/ncm_windows_day2',
              'ncm_windows_ad3/ncm_windows_marketplace',
            ],
    },
  ],
};
